Add new folder for batch processing scripts
BazisSoft/Scripts pull request #5
Opened 2017-04-17 12:43 UTC by Let0s

2017-04-17 13:00 UTC, quanterion requested changes

2017-04-17 13:00 UTC, quanterion commented on Пакетная обработка/Замена материала.js
> +        }
В конце думаю стоит сделать Model.Build() иначе визуально последняя обработанная модель будет видна в старых материалах

2017-04-17 13:00 UTC, quanterion commented on Пакетная обработка/Замена материала.js
> +    let names = fs.readdirSync('./');
хардколить текущую папку здесь тоже нехорошо
1)папка должна быть параметром ChangeMaterial
2)дефолтное значение придумать по хитрее.. например выдрать папку текущего открытого файла

2017-04-17 13:00 UTC, quanterion commented on Пакетная обработка/Замена материала.js
> +            Action.Commit();
Неплохо бы добавить инфы, например в конце функции выдавать сообщение что на что поменяли, во скольких файлах и во скольких объектах

2017-04-17 13:00 UTC, quanterion commented on Пакетная обработка/Замена материала.js
> +        }
Стоит добавить флаг, заменялись ли материалы в модели . Если нет - не сохранять её, чтобы не менять дату последнего изменения

2017-04-19 11:52 UTC, quanterion approved these changes

2017-04-19 11:52 UTC, quanterion commented on Пакетная обработка/Замена материала.js
> +    let count = 0;
fileIndex

2017-05-25 08:26 UTC, Let0s commented on Пакетная обработка/Замена материала.js
> +    let count = 0;
@quanterion, fixed

2017-05-30 06:11 UTC, merged